version: "3.3"

services: 
  rfxcom2mqtt:
    image: rverpillot/rfxcom2mqtt
    container_name: rfxcom2mqtt
    build: ./
    volumes:
      - ./config:/app/data
    ports:
      - 8891:8891
    #devices:
    #  - /dev/ttyUSB1:/dev/ttyUSB0
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
